//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Agendado
    {
        [Display(Name = "Agendamento")]
        public int Codigo_Agendado { get; set; }
        public Nullable<int> Codigo_Agenda { get; set; }
        //[Required(ErrorMessage = "Campo Necessário.")]
        public Nullable<int> Codigo_Pessoa { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        [Display(Name = "Médico")]
        public Nullable<int> Codigo_Medico { get; set; }
        public Nullable<int> Codigo_Local { get; set; }
        public Nullable<int> Codigo_Pre_Consulta { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        [Display(Name = "Data da Consulta")]
        public Nullable<System.DateTime> Data_Consulta { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        [Display(Name = "Hora da Consulta")]
        public Nullable<System.TimeSpan> Hora_Consulta { get; set; }
        [Display(Name = "Confirmação")]
        public Nullable<bool> Consulta_Confirmada { get; set; }
        public string NomeMedico { get; set; }

        public virtual Agenda Agenda { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Local Local { get; set; }
        public virtual Pre_Consulta Pre_Consulta { get; set; }
    }
}
