//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agenda()
        {
            this.Agendado = new HashSet<Agendado>();
        }
    
        public int Codigo_Agenda { get; set; }
        public Nullable<int> Codigo_Medico { get; set; }
        public Nullable<System.DateTime> Data_Agenda { get; set; }
        public Nullable<System.TimeSpan> Hora_Agenda { get; set; }
        public Nullable<double> Duracao_Consulta { get; set; }
        public Nullable<bool> Horario_Livre { get; set; }
    
        public virtual Medico Medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendado> Agendado { get; set; }
    }
}
