//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Endereco()
        {
            this.Local = new HashSet<Local>();
            this.Pessoa = new HashSet<Pessoa>();
        }
        [Display(Name ="Endereço")]
        public int Codigo_Endereco { get; set; }
        public Nullable<int> Codigo_Cidade { get; set; }

        [Required(ErrorMessage = "Campo Necessário.")]

        [Display(Name = "Logradouro")]
        public string Endereco1 { get; set; }

        public Nullable<int> Numero { get; set; }
        public string Complemento { get; set; }

        [Required(ErrorMessage = "Campo Necessário.")]
        public string Bairro { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Local> Local { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}
