//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Especialidade
    {

        [Display(Name = "Codigo Especialidade")]
        public int Codigo_Especialidade { get; set; }

        [Display(Name = "Codigo Medico")]
        public Nullable<int> Codigo_Medico { get; set; }

        [Display(Name = "Especialidade")]
        public string Especialidade1 { get; set; }
    
        public virtual Medico Medico { get; set; }
    }
}
