//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_Medico
    {
        public int Codigo_Horario_Medico { get; set; }
        public Nullable<int> Codigo_Medico { get; set; }
        public Nullable<int> Codigo_Local { get; set; }
        public string Dia_Semana { get; set; }
        public Nullable<System.TimeSpan> Hora_Entrada { get; set; }
        public Nullable<System.TimeSpan> Hora_Saida { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Local Local { get; set; }
    }
}
