//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Agendado = new HashSet<Agendado>();
            this.Consulta = new HashSet<Consulta>();
            this.Horario_Medico = new HashSet<Horario_Medico>();
            this.Sala_Espera = new HashSet<Sala_Espera>();
        }
    
        [Display(Name ="Médico")]
        public int Codigo_Medico { get; set; }
        public Nullable<int> Codigo_Pessoa { get; set; }
        public Nullable<int> Codigo_Estado { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]

        [Display(Name = "Data de Admissão")]
        public Nullable<System.DateTime> Data_Admissao { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        public Nullable<int> CRM { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        public Nullable<int> Codigo_Especialidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendado> Agendado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual Descricao_Especialidade Descricao_Especialidade { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario_Medico> Horario_Medico { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sala_Espera> Sala_Espera { get; set; }
    }
}
