//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.Agendado = new HashSet<Agendado>();
            this.Consulta = new HashSet<Consulta>();
            this.Medico = new HashSet<Medico>();
            this.Sala_Espera = new HashSet<Sala_Espera>();
            this.Secretaria = new HashSet<Secretaria>();
        }
    
        public int Codigo_Pessoa { get; set; }
        [Display(Name = "Usuário")]
        public Nullable<int> Codigo_Acesso { get; set; }
        [Display(Name = "Endereço")]
        public Nullable<int> Codigo_Endereco { get; set; }

        [Required(ErrorMessage = "Campo Necessário.")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        public string CPF { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        public string RG { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]

        [Display(Name = "Data de Nascimento")]
        public Nullable<System.DateTime> Data_Nascimento { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        [Display(Name = "Estado Civil")]
        public string Estado_Civil { get; set; }

        public string Telefone { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        public string Celular { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Campo Necessário.")]
        public string Sexo { get; set; }
    
        public virtual Acesso Acesso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendado> Agendado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual Endereco Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medico> Medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sala_Espera> Sala_Espera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Secretaria> Secretaria { get; set; }

        public string CPFErrorMessage { get; set; }
    }
}
