//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pre_Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pre_Consulta()
        {
            this.Agendado = new HashSet<Agendado>();
            this.Consulta = new HashSet<Consulta>();
            this.Sala_Espera = new HashSet<Sala_Espera>();
        }
    
        public int Codigo_Pre_Consulta { get; set; }
        public string Sintomas { get; set; }

        [Display(Name = "Tomando algum Medicamento")]
        public string Remedios_Tomando { get; set; }

        [Display(Name = "Diagnósticos Anteriores")]
        public string Diagnostico_Anterior { get; set; }

        [Display(Name = "Observações")]
        public string Observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendado> Agendado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sala_Espera> Sala_Espera { get; set; }
    }
}
