//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala_Espera
    {
        public int Codigo_Sala_Espera { get; set; }
        public Nullable<int> Codigo_Pessoa { get; set; }
        public Nullable<int> Codigo_Medico { get; set; }
        public Nullable<int> Codigo_Pre_Consulta { get; set; }
        public Nullable<double> Duracao_Consulta { get; set; }
        public Nullable<System.TimeSpan> Hora_Chegada_Paciente { get; set; }
        public Nullable<System.TimeSpan> Inicio_Consulta { get; set; }
        public Nullable<System.TimeSpan> Fim_Consulta { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pre_Consulta Pre_Consulta { get; set; }
    }
}
