//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBenner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretaria
    {
        public int Codigo_Secretaria { get; set; }
        public Nullable<int> Codigo_Pessoa { get; set; }
        public Nullable<System.DateTime> Data_Admissao { get; set; }
        public Nullable<System.TimeSpan> Hora_Entrada { get; set; }
        public Nullable<System.TimeSpan> Hora_Saida { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
